# Generated by Django 5.1 on 2024-08-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='BIO',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
