# Generated by Django 5.0.6 on 2024-06-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('courseNumber', models.CharField(max_length=7, primary_key=True)),
                ('title', models.CharField(max_length=120)),
                ('language', models.CharField(max_length=15)),
                ('courseType', models.CharField(max_length=10)),
                ('schedule', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
