# Generated by Django 5.0.6 on 2024-06-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_info', '0002_remove_courseinfo_description_courseinfo_course_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinfo',
            old_name='notAppicableWith',
            new_name='notApplicableWith',
        ),
    ]
