# Generated by Django 5.0.6 on 2024-07-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_info', '0004_remove_courseinfo_recomendedprerequisites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='courseNumber',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
