# Generated by Django 5.0.6 on 2024-07-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_info', '0005_alter_courseinfo_coursenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='courseNumber',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
