# Generated by Django 5.0.6 on 2024-08-05 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_info', '0007_alter_courseinfo_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfo',
            name='completed',
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='content',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='course_responsible',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='credits',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='evaluation_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='exam_aids',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='exam_duration',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='general_course_objectives',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='learing_objectives',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='location',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='teachers',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='type_of_assessment',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DegreeRequirements',
            fields=[
                ('degree_id', models.IntegerField(primary_key=True, serialize=False)),
                ('degree_name', models.CharField(max_length=50)),
                ('required_courses', models.ManyToManyField(blank=True, related_name='required_courses', to='course_info.courseinfo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_courses', models.ManyToManyField(blank=True, related_name='completed_courses', to='course_info.courseinfo')),
                ('degree_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_info.degreerequirements')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elective_courses', models.ManyToManyField(blank=True, related_name='courses', to='course_info.courseinfo')),
                ('degree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_info.degreerequirements')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_info.user')),
            ],
        ),
    ]
