# Generated by Django 5.1 on 2024-08-14 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GeneralData', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GeneralData.degree')),
                ('elective_courses', models.ManyToManyField(blank=True, related_name='course_plans', to='GeneralData.course')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoursePlanner.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_date', models.CharField(max_length=20)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='CoursePlanner.courseplan')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_taken', models.BooleanField(default=False)),
                ('grade', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtu_courses', to='GeneralData.course')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_courses', to='CoursePlanner.semester')),
            ],
        ),
    ]
