# Generated by Django 5.1 on 2024-08-14 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('CoursePlanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseplan',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.profile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
